/***********************************************************************/
/*                                                                     */
/*  FILE        :64128E.c                                              */
/*  DATE        :Tue, Sep 18, 2007                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :1B                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.8).     */
/*                                                                     */
/***********************************************************************/
#include "64x128GLCD.h"
#include <utils.h>
#include <includes.h>

#define	HIGH	1
#define	LOW	0

/* writes particular command byte to lcd */
void LCD_WRITE_CMD(unsigned char cmd)
{
	LCD_CTRL_CLR |= LCDRS;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_DATA_CLR = GLCD_DATA_MASK;
	LCD_DATA_SET = cmd << 15;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDRS;
	__asm("NOP");
//	__asm("NOP");
}

/* writes particular data byte to lcd */
void LCD_WRITE_DATA(unsigned char data)
{
	LCD_CTRL_SET |= LCDRS;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_DATA_CLR = GLCD_DATA_MASK;
	LCD_DATA_SET = data << 15;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDRS;	
	__asm("NOP");
//	__asm("NOP");
 }

unsigned char LCD_READ_DATA(void)
{
	unsigned char rd = 0;
	
	LCD_CTRL_SET |= LCDRS;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_DATA_DIR &= ~(GLCD_DATA_MASK);
	rd = (FIO1PIN & GLCD_DATA_MASK) >> 15;
	LCD_DATA_DIR |= GLCD_DATA_MASK;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDRW;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDCS1B;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_CLR |= LCDRS;	
	__asm("NOP");
//	__asm("NOP");		
	
	return rd;
 }

void LCD_INIT(void)
{
	LCD_CTRL_CLR |= LCDRST;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_CTRL_SET |= LCDRST;
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xE2);		// S/W RESWT
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xA0);		// ADC select	
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xC8);  	// SHL Normal
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xA3);		// LCD bias
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x2F);		// Power control
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x22);		// reg resistor select
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x40);		// Initial display line 40
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xA4);		// Normal display
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xA6);		// REverce display a7
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x81);		// Ref vg select mode
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x3f);		// Ref vg reg select
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0xAF);		// Display ON
	__asm("NOP");
//	__asm("NOP");	 
	
	LCD_WRITE_CMD(0XB0);		// Set page address
	__asm("NOP");
//	__asm("NOP");
	
	LCD_WRITE_CMD(0x10);		// Set coloumn addr  MSB 
	__asm("NOP");
//	__asm("NOP");		 
	
	LCD_WRITE_CMD(0x00);		// Set coloumn addr LSB
	__asm("NOP");
//	__asm("NOP");
}
 
/* set the cursor to perticular page and coloumn */
void LCD_SET_PAGE(unsigned char page,unsigned char col)
{
	unsigned char msb,lsb;
	msb		=	(((col & 0xF0) >> 4)| 0x10);
	lsb		=	(col & 0x0F);
	LCD_WRITE_CMD(page);
	LCD_WRITE_CMD(msb);
	LCD_WRITE_CMD(lsb);
}

/* clears entire lcd or clears all page*/
void LCD_CLEAR(void)
{
	unsigned char i = 0,j = 0;
	
	LCD_SET_PAGE(PAGE1,COL1);		// initial page, col
		
	for(i = 0; i < 8; i ++)
	{
          for(j = 0; j < 128; j ++)
            LCD_WRITE_DATA(0x00);
          LCD_SET_PAGE(PAGE1 + i + 1 , COL1);	// increment page
	}
	
	LCD_SET_PAGE(PAGE1,COL1);		// initial page,col
}
